### ISSUE TITLE
Reading fchk file

### ISSUE THREAD

**Issue by rafa-pr** [efposadac/openLOWDIN#103]
Dear all, 

I want to read a fchk file in order to pass the coefficients and density matrix generated with gaussian to a lowdin calculation that doesnt perform the SCF procedure.

Was including the following CONTROL lines:

1. readFchk  = T
2. noSCF = T

However i was getting an error from the Molecular_system subroutine for reading this file. Tried renaming it to the same as the input, for example test.lowdin (input) and including a "test.fchk" file on the same directory but got the same issue on "no fchk file found". Also tried with other names for the fchk file with no success. 

Additionally, i would like to ask if theres a possibility for LOWDIN to read a wfn file (either a .vec file or a fchk one) only for electrons and perform the SCF for another quantum species (positron in a more specific case). I would like to use the coefficients and density matrix calculated for electrons and pass that one for a calculation of a system that includes a positron. For example (not the case but something in mind) i get a CISD wfn for electrons in say CH3OH and want to keep those coeffcients and run the CH3OH:e+ system so it solves HF for the whole system generating the solution for the positron.

Hopefully we can discuss this and thanks in advance.

Have a good one.

**Comment by fsmoncadaa** [comment]
Hello Rafa!

Your first question points to two issues in the code.
First, the "lowdin" bash script it is not moving the *fchk files from the input folder to the scratch folder.
Second, the code is expecting a fchk for each species in the system. If you have positrons and electrons, and the input is named "test.lowdin", it will search for "test.E-.fchk" and "test.POSITRON.fchk". If it fails to find any of them, it will throw the error. These two issues are easy to fix. 

As for your second question, you can do that with lowdin using ".vec" or ".plainvec" files. If you pass a file that doesn't contain the coefficients for the positron, it will read the coefficients for the E-, use them to compute its density matrix, and then it will do the hcore guess for the positron. See the files attached for a example.
In the output it will print:
" Combination coefficients for E-ALPHA were read from H.APMO.READCOEFF.plainvec
 Combination coefficients for E-BETA were read from H.APMO.READCOEFF.plainvec
       Usign  HCORE density guess for species:        H_1"
[readCoeff.zip](https://github.com/user-attachments/files/17934486/readCoeff.zip)

I'm currently working on a branch fixing small things, so I might fix the fchk error this week, and add some tests with fchk files to avoid having these problems in the future

Cheers
