### ISSUE TITLE
Bug in ConstantsOfCoupling, change Warning to Error

### ISSUE THREAD

**Issue by fsmoncadaa** [efposadac/openLOWDIN#11]
This input file:

GEOMETRY
        O   6-311G     0.000000      0.000000     -0.066575
        e-[H]   6-311G     0.000000      0.754175      0.528381
        e-[H]   6-311G     0.000000     -0.754174      0.528382
        O        dirac     0.000000      0.000000     -0.066575
        H-a_1   Nakai-5-spd     0.000000      0.754175      0.528381
        H-b_1   Nakai-5-spd    0.000000     -0.754174      0.528382	
END GEOMETRY

TASKS
        method = "RHF"
END TASKS

Results in an infinite loop of prints of
 
 !!! WARNING !!!
    Debug description: In ConstantsOfCoupling at load function.
    Description: Elemental particle: O NOT found!!
 !!!

**Comment by jacharrym** [comment]
What is this test? e-(O) missing?

**Comment by fsmoncadaa** [comment]
exactly!
