### ISSUE TITLE
Error in tests.

### ISSUE THREAD

**Issue by efposadac** [efposadac/openLOWDIN#17]
One of the tests fails, but it looks ok. The epsilon may be too strict. Should we change it to 1.0e-7?
```
HF energy [-92.903413350633, 1e-08] -92.90341333695 1.368300672766054e-08
HCN.e+.gribakin.uhf ... NOT OK
```

**Comment by fsmoncadaa** [comment]
The SCF energy tolerance of that test is 1E-8, seems reasonable to increase the epsilon of the test
