### ISSUE TITLE
Order of the G functions for molden file

### ISSUE THREAD

**Issue by fsmoncadaa** [efposadac/openLOWDIN#29]
When writing a molden output, we call the MolecularSystem_changeOrbitalOrder routine

This routine for the G functions seems not to be working properly. For example, when we load the molden file produced by this input

SYSTEM_DESCRIPTION='Molecula de H2O'

GEOMETRY
        e-[O]   CC-PVQZ    0.000000      0.000000     -0.066575
        e-[H]   6-31G  0.000000      0.754175      0.528381
        e-[H]   6-31G  0.000000     -0.754174      0.528382
        O     dirac  0.000000      0.000000     -0.066575
        H_1   dirac    0.000000      0.754175      0.528381
        H_1   dirac    0.000000     -0.754174      0.528382
END GEOMETRY

TASKS
        method = "RHF"
END TASKS

OUTPUTS
        moldenFile
END OUTPUTS

Molden computes:
Sum of Mulliken Charges:   0.0201

This number should be zero!

The sum of Mulliken Charges becomes zero if we replace the CC-PVQZ with  CC-PVTZ basis. That's why I think the order of the G functions may be incorrect

**Comment by jacharrym** [comment]
I think the ordering between molden and gamess is different for G. Maybe there is an option to switch format. Or maybe I'm crazy...

**Comment by fsmoncadaa** [comment]
We have the option to switch from Molden to Gamess ordering. In Gamess we only go up to F functions, following the comments, for molden I'm taking the G ordering from the fchk file needed for Erkale. But this doesn't seem to be the correct order for molden

**Comment by jacharrym** [comment]
Ah Ok, so then for G we simply never checked the order. Probably we just added a warning

https://www.theochem.ru.nl/molden/molden_format.html

**Comment by fsmoncadaa** [comment]
Muchas gracias don Jorge!

Definitively the order is wrong

Molden expected format

   9G: G 0, G+1, G-1, G+2, G-2, G+3, G-3, G+4, G-4
  15G: xxxx yyyy zzzz xxxy xxxz yyyx yyyz zzzx zzzy,
       xxyy xxzz yyzz xxyz yyxz zzxy
 
Current order in the code:
           !! Reorder the G functions                                                                                                                 
           !! counter:   0,  1,   2,   3,   4,   5,   6,   7,   8    9,   10,  11,  12,  13,  14                                                      
           !! Lowdin:  XXXX,XXXY,XXXZ,XXYY,XXYZ,XXZZ,XYYY,XYYZ,XYZZ,XZZZ,YYYY,YYYZ,YYZZ,YZZZ,ZZZZ                                                     
           !! erkale-FCHK:  ZZZZ,YZZZ,YYZZ,YYYZ,YYYY,XZZZ,XYZZ,XYYZ,XYYY,XXZZ,XXYZ,XXYY,XXXZ,XXXY,XXXX
