### ISSUE TITLE
Check default nuclear masses

### ISSUE THREAD

**Issue by fsmoncadaa** [efposadac/openLOWDIN#31]
When we were running calculations with ^3He we noticed that the default mass (5494.8926 a.u.) is not exactly the mass of the isotope minus two electrons (5495.88509 a.u.).
The mass for this isotope in the lib/databases/atomicElements.lib is the correct one. 
Are we still calculating the mass of the nucleus as the sum of the number of protons and electrons? (This is not an exact estimate)
We should update the default mass for the nucleus to first read the atomicElements.lib file and then if the mass is not found estimate it from the number of protons and neutrons

**Comment by jacharrym** [comment]
I agree
