### ISSUE TITLE
input lowercase/uppercase sensitivity

### ISSUE THREAD

**Issue by fsmoncadaa** [efposadac/openLOWDIN#36]
Some parts of the input are lowercase/uppercase sensitive, and I don't think they should be.

For instance, replacing ionizeSpecie="POSITRON" with ionizeSpecie="Positron" in the following input results in an error. 

GEOMETRY
e-(F) DEF2-TZVPPD               0.0                       0.0        0.0 addParticles=1 multiplicity=1
F     dirac                     0.0                       0.0        0.0
E+    PSX-TZ                    0.0                       0.0        0.0
END GEOMETRY

TASKS
        method = "UHF"
        propagatorTheoryCorrection = 3
END TASKS

CONTROL
        ptP3Method = "REN-P3"
!This line gives error
!       ionizeSpecie = "Positron"
!This line works fine
        ionizeSpecie = "POSITRON"
        ionizeMO= 1
	ptJustOneOrbital=.T.
END CONTROL

**Comment by efposadac** [comment]
Everything should be converted to lowercase or uppercase when parsed.
