### ISSUE TITLE
MOfractionOccupation=0.0 gives NaN 

### ISSUE THREAD

**Issue by fsmoncadaa** [efposadac/openLOWDIN#49]
The SCF of an input like this converges fine, but the ionized orbital coefficients and the energy become NaN 

GEOMETRY
e-(Li)  cc-pVTZ   0.0000        0.0000  1.5949   multiplicity=1
e-(H)   cc-pVTZ   0.0000        0.0000  0.00000
Li      dirac     0.0000        0.0000 1.5949
H_1     dirac     0.0000        0.0000 0.0000
END GEOMETRY

TASKS
        method = "UHF"
END TASKS

CONTROL
        readCoefficients=F
        ionizeSpecies="E-ALPHA"
        IonizeMO=2
        MOfractionOccupation=0.0 
!works fine with any other number such as MOfractionOccupation=0.00000001
END CONTROL

**Comment by fsmoncadaa** [comment]
Also in this regard, I'll add some test of the "exchangeOrbitalsInSCF" that is invoked when we use fractional occupations

**Comment by jacharrym** [comment]
push the commit

**Comment by fsmoncadaa** [comment]
Solved in my last commit
