### ISSUE TITLE
Add method/test/examples for CISD-

### ISSUE THREAD

**Issue by fsmoncadaa** [efposadac/openLOWDIN#59]
CISD- is Tachikawa CI method with only mixed electron+positron doubles excitation
CISD+ includes all the doubles plus mixed electron+positron triples

**Comment by fsmoncadaa** [comment]
I'm adding in my next commit a test for CISD+. CISD- extension will still be open

**Comment by jacharrym** [comment]
Added in commit 165fd400dbb8ae3c1b25f4140a719cf9c6eec972

**Comment by jacharrym** [comment]
Added in commit 165fd400dbb8ae3c1b25f4140a719cf9c6eec972
