### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by Physfock** [efposadac/openLOWDIN#81]
Can authors add more examples of calculating some classical systems like muonic/antiprotonic helium?

**Comment by fsmoncadaa** [comment]
I'm not sure what you mean by classical. But, If I had to get a starting point for muonic/antiprotonic helium I would use an input like the following, where in the XXXXXX I would put the reduced mass of muonic helium (201.1) or of antiprotonic helium (1466.8):

GEOMETRY
	e-[H]  aug-cc-pVTZ    0.0000  0.0000  0.0000 multiplicity=2
	U-     CUSTOM    0.0000  0.0000  0.0000 m=XXXXXX
	He    dirac    0.0000  0.0000  0.0000
END GEOMETRY

TASKS
	method = "UHF"
END TASKS

BASIS CUSTOM
O-U- U- (16S) BASIS TYPE: 2
# (1S)-[1S]
16
1 0 1
470.63607188 1.00000000
2 0 1
1013.95467961 1.00000000
3 0 1
2184.49913585 1.00000000
4 0 1
4706.36071854 1.00000000
5 0 1
10139.54679568 1.00000000
6 0 1
21844.99135749 1.00000000
7 0 1
47063.60718332 1.00000000
8 0 1
101395.46795228 1.00000000
9 0 1
218449.91356518 1.00000000
10 0 1
470636.07181232 1.00000000
11 0 1
1013954.67947779 1.00000000
12 0 1
2184499.13555478 1.00000000
13 0 1
4706360.71791422 1.00000000
14 0 1
10139546.7947779 1.00000000
15 0 1
21844991.3555478 1.00000000
16 0 1
47063607.1791422 1.00000000
14 0 1
101395467.947779 1.00000000
15 0 1
218449913.555478 1.00000000
16 0 1
470636071.791422 1.00000000
END BASIS

**Comment by Physfock** [comment]
> I'm not sure what you mean by classical. But, If I had to get a starting point for muonic/antiprotonic helium I would use an input like the attached file, where in the XXXXXX I would put the reduced mass of muonic helium (201.1) or of antiprotonic helium (1466.8), and rename it to have .lowdin extension [He-e-X-CUSTOM_MASS.txt](https://github.com/user-attachments/files/15536315/He-e-X-CUSTOM_MASS.txt)
> 
> This is a simple HF calculation, where the mass of the negative particle is given directly from the input. The large even-tempered basis set should provide coverage for the highly localized densities of the muon and antiproton.
> 
> with m=201.1 I got TOTAL ENERGY = -402.696687921461 VIRIAL RATIO (V/T) = 2.000024358632
> 
> and with m=1466.8 TOTAL ENERGY = -2926.149607172766 VIRIAL RATIO (V/T) = 2.007799376011

Thanks for the answer! Following your example, I got a satisfactory value for the ground state of the muonic helium atom.
The input below results in: -402.603948593154 a.u. while Hylleraas approach (exact variational solution for 3-body atomic problem) gives - 402.637332175538 a.u. (http://dx.doi.org/10.1051/epjconf/201922203009)

I slightly modify your suggestion as follows: 

SYSTEM_DESCRIPTION='HeU Atom'

GEOMETRY
e-[He] aug-cc-pVQZ   0.0000 0.0000 0.0000 multiplicity=2 addParticles=-1
U- 13s.ET.HE.U.TF    0.0000 0.0000 0.0000 m=201.1
He dirac             0.0000 0.0000 0.0000
END GEOMETRY

TASKS
method = "UHF"
configurationInteractionLevel ="FCI"
END TASKS

However, I could not understand why in the manual (right at the beginning) when calculating "muonic water" the reduced mass for the muon never appears in the input geometry?

**Comment by fsmoncadaa** [comment]
Hi, 

I'm glad that you found a input that is working

Our manual unfortunately is a bit outdated. In the next update we will add the reduced mass option to the input description figure. Thanks for pointing this out
