### ISSUE TITLE
Positive muons, examples

### ISSUE THREAD

**Issue by Physfock** [efposadac/openLOWDIN#82]
I am seeking guidance on how to incorporate positive muons into my molecule. I have already done this, but could not add the corresponding basis set (there are no such basis in libraries). Despite reviewing the tutorial, I have been unable to identify a relevant example. Additionally, I would appreciate if you could provide some references on the fundamental principles of basis set construction.

**Comment by fsmoncadaa** [comment]
You can add custom basis sets in the Input, like in this file (here is for a negative muon)
https://github.com/efposadac/openLOWDIN/blob/master/test/HemuH-CUSTOM_BASIS.lowdin

Also you can add your custom basis set files in 
lib/basis/
and copy them to the working directory with 
make install

To generate basis, you can start by using a large even-tempered basis set, like the 14s14p14d in 
https://doi.org/10.1063/5.0077179
this will give results very close to the basis set limit.
If you want a more computationally efficient approach, you can start from a small basis set, like the 1s1p1d of
https://doi.org/10.1016/S0009-2614(02)00881-3
and then add functions until the energy of some test molecule converges 

I hope this helps
